# Generated by Django 5.0.3 on 2024-03-16 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_continents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, unique=True, verbose_name='Country Name')),
                ('country_continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_continents.continent', verbose_name='Continent Id')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'country',
            },
        ),
    ]
